name = "randoneering-llc-hugo"
license = "MIT"
licenselink = "https://github.com/randoneering/randoneering-llc-hugo/blob/master/LICENSE"
description = "Fork of zerostaticthemes' Hero Hugo Theme, modified for Randoneering, LLC."

homepage = "https://github.com/randoneering/randoneering-llc-hugo"

tags = ["responsive","minimal","clean","company","portfolio","bootstrap","zerostatic"]
features = ["services","work","fullwidth","hero images"]

[author]
  name = "Robert Austin"
  homepage = "https://www.zerostatic.io"
[author]
  name = "Justin Frye"
  homepage = "https://randoneering.tech"
